CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE roles(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text UNIQUE NOT NULL);
CREATE TABLE users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),email text UNIQUE NOT NULL,password_hash text NOT NULL,active boolean DEFAULT true,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE user_roles(user_id uuid REFERENCES users,role_id uuid REFERENCES roles,PRIMARY KEY(user_id,role_id));
CREATE TABLE suppliers(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),supplier_code text UNIQUE NOT NULL,legal_name text NOT NULL,country text,region text,risk_score numeric(5,2),risk_band text,version int DEFAULT 1,deleted_at timestamptz,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE programs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),code text UNIQUE NOT NULL,name text NOT NULL);
CREATE TABLE commodities(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),code text UNIQUE NOT NULL,name text NOT NULL);
CREATE TABLE components(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),part_number text UNIQUE NOT NULL,description text,commodity_id uuid REFERENCES commodities,program_id uuid REFERENCES programs,current_supplier_id uuid REFERENCES suppliers,annual_demand numeric,current_price numeric(18,4),currency char(3),single_source boolean DEFAULT false,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE supplier_sites(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),supplier_id uuid REFERENCES suppliers,address jsonb,country text,capacity_utilization numeric);
CREATE TABLE supplier_contacts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),supplier_id uuid REFERENCES suppliers,name text,email text);
CREATE TABLE supplier_performance(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),supplier_id uuid REFERENCES suppliers,period date,otif numeric,defect_ppm numeric,capacity_utilization numeric);
CREATE TABLE supplier_risk_assessments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),supplier_id uuid REFERENCES suppliers,model_version text,score numeric,band text,confidence numeric,inputs jsonb,contributions jsonb,created_at timestamptz DEFAULT now());
CREATE TABLE rfqs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),rfq_number text UNIQUE NOT NULL,title text,status text,program_id uuid REFERENCES programs,due_date date,version int DEFAULT 1,created_at timestamptz DEFAULT now());
CREATE TABLE rfq_components(rfq_id uuid REFERENCES rfqs,component_id uuid REFERENCES components,PRIMARY KEY(rfq_id,component_id));
CREATE TABLE rfq_suppliers(rfq_id uuid REFERENCES rfqs,supplier_id uuid REFERENCES suppliers,PRIMARY KEY(rfq_id,supplier_id));
CREATE TABLE quotations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),rfq_id uuid REFERENCES rfqs,supplier_id uuid REFERENCES suppliers,status text,currency char(3),created_at timestamptz DEFAULT now());
CREATE TABLE quotation_lines(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),quotation_id uuid REFERENCES quotations,component_id uuid REFERENCES components,unit_price numeric(18,4),tooling_price numeric(18,2),freight numeric(18,4),lead_time_days int);
CREATE TABLE cost_models(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text,commodity_id uuid REFERENCES commodities);
CREATE TABLE cost_model_versions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),cost_model_id uuid REFERENCES cost_models,version int,formula jsonb,weights jsonb,UNIQUE(cost_model_id,version));
CREATE TABLE should_cost_calculations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),component_id uuid REFERENCES components,model_version_id uuid REFERENCES cost_model_versions,inputs jsonb,total numeric(18,4),created_at timestamptz DEFAULT now());
CREATE TABLE should_cost_elements(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),calculation_id uuid REFERENCES should_cost_calculations,name text,amount numeric(18,4));
CREATE TABLE sourcing_scenarios(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text,baseline_id uuid REFERENCES sourcing_scenarios,seed int,created_at timestamptz DEFAULT now());
CREATE TABLE scenario_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),scenario_id uuid REFERENCES sourcing_scenarios,event_type text,parameters jsonb);
CREATE TABLE scenario_results(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),scenario_id uuid REFERENCES sourcing_scenarios,metrics jsonb,methodology_version text);
CREATE TABLE award_recommendations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),rfq_id uuid REFERENCES rfqs,model_version text,score_detail jsonb,confidence numeric,status text,override_reason text);
CREATE TABLE award_splits(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),recommendation_id uuid REFERENCES award_recommendations,supplier_id uuid REFERENCES suppliers,percentage numeric);
CREATE TABLE audit_logs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),actor_id uuid REFERENCES users,action text,record_type text,record_id uuid,before_state jsonb,after_state jsonb,request_id text,created_at timestamptz DEFAULT now());
CREATE TABLE application_settings(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),key text UNIQUE,value jsonb,version int DEFAULT 1);
CREATE TABLE ai_conversations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid REFERENCES users,created_at timestamptz DEFAULT now());
CREATE TABLE ai_messages(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),conversation_id uuid REFERENCES ai_conversations,role text,content text,confidence numeric);
CREATE TABLE ai_citations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),message_id uuid REFERENCES ai_messages,record_type text,record_id uuid,label text);
