"use client";
import {useState} from "react";

const nav=["Control Tower","Suppliers","Components","Commodities","RFQs","Should Cost","Risk Intelligence","Digital Twin","Negotiation","Reports","AI Copilot","Administration"];
const stats=[["Addressable spend","$48.2M","↗ 6.4% vs plan"],["Annualized savings","$3.74M","↗ 77% of target"],["Active RFQs","18","6 due this week"],["High-risk suppliers","7","! 2 require action"],["Single-source exposure","$8.6M","! 17.8% of spend"],["Average OTIF","94.2%","↗ 1.8 pts"],["Defect PPM","612","↘ 84 this quarter"],["Should-cost gap","8.7%","$2.1M opportunity"]];
const vendors=[
 ["Apex Forge Systems","SUP-1001 · Mexico","$42.80","72","68 · High","$51.42","76","NOT RECOMMENDED"],
 ["Northstar Fabrication","SUP-1014 · United States","$45.60","91","22 · Low","$47.18","91","PRIMARY · 70%"],
 ["Great Lakes Precision","SUP-1022 · Canada","$47.10","86","31 · Moderate","$48.26","84","SECONDARY · 30%"]
];
export default function Home(){
 const[active,setActive]=useState("Control Tower"),[copilot,setCopilot]=useState(false),[light,setLight]=useState(false);
 return <main className={light?"light":""}>
  <aside><div className="brand"><b>ST</b><div>SOURCE TWIN<small>AI</small></div></div><nav>{nav.map((n,i)=><button className={n===active?"active":""} onClick={()=>setActive(n)} key={n}><i>{["⌂","◇","▣","⬡","◫","∑","△","◎","◈","▤","✦","⚙"][i]}</i>{n}{n==="Risk Intelligence"&&<em>7</em>}</button>)}</nav><div className="user"><span>EM</span><div><b>Elena Morris</b><small>Sourcing Manager</small></div></div></aside>
  <section className="shell"><header><div className="search">⌕ <input placeholder="Search suppliers, RFQs, components…"/><kbd>⌘ K</kbd></div><button onClick={()=>setLight(!light)}>{light?"☾":"☼"}</button><button>♢<sup>3</sup></button><button className="ask" onClick={()=>setCopilot(true)}>✦ Ask Copilot</button></header>
   <div className="content"><div className="heading"><div><small>CONTROL TOWER　/　ENTERPRISE OVERVIEW</small><h1>Good morning, Elena.</h1><p>Here’s what needs your attention across the supply base.</p></div><div><button>⚙ Filters <b>3</b></button><select><option>Last 12 months</option><option>Year to date</option></select><button>⇩ Export</button></div></div>
    <div className="alert"><b>!</b><div><strong>2 critical supply-continuity alerts</strong><p>A four-week disruption at Apex Forge Systems puts $3.2M of program revenue at risk.</p></div><button>Review alerts →</button></div>
    <div className="stats">{stats.map((s,i)=><article key={s[0]}><small>{s[0]}</small><strong>{s[1]}</strong><p className={i===3||i===4?"warn":"good"}>{s[2]}</p><svg viewBox="0 0 90 25"><polyline points={i%2?"0,19 15,16 30,17 45,11 60,13 75,5 90,3":"0,20 15,18 30,19 45,12 60,14 75,7 90,5"}/></svg></article>)}</div>
    <div className="split"><section className="panel"><div className="panelhead"><div><h2>Spend by commodity</h2><p>$48.2M total addressable spend</p></div>•••</div><div className="bars">{[["Structural fabrication","$12.4M",100],["CNC machining","$9.8M",79],["Stamping","$7.2M",58],["Injection molding","$6.4M",52],["Die casting","$5.1M",41],["Other","$7.3M",59]].map((x,i)=><div key={x[0]}><span>{x[0]}</span><i><b style={{width:x[2]+"%",background:["#5686ff","#35c7a5","#9473f5","#e9aa52","#e67280","#59667d"][i]}}/></i><strong>{x[1]}</strong></div>)}</div></section>
     <section className="panel"><div className="panelhead"><div><h2>Supplier risk distribution</h2><p>30 active suppliers · weighted risk model v2.4</p></div><a>View model →</a></div><div className="risk"><div className="donut"><span><b>38</b><small>AVG RISK</small></span></div><div>{[["Low",14,"green"],["Moderate",9,"yellow"],["High",5,"orange"],["Critical",2,"red"]].map(x=><p key={x[0]}><i className={String(x[2])}/>{x[0]}<b>{x[1]}</b></p>)}</div></div><div className="note">ⓘ Missing data lowers confidence—not risk.</div></section></div>
    <section className="panel award"><div className="panelhead"><div><h2>RFQ-2026-001 · Award recommendation</h2><p>Welded structural assembly · Eastern Ridge EV program</p></div><span>AWAITING APPROVAL</span></div><div className="recommend"><b>★</b><div><small>RECOMMENDED AWARD</small><strong>Northstar Fabrication <em>Primary · 70%</em></strong><p>Best risk-adjusted value despite a 6.5% price premium.</p></div><button onClick={()=>setCopilot(true)}>View explanation →</button></div><div className="table"><table><thead><tr><th>SUPPLIER</th><th>QUOTE</th><th>SHOULD COST</th><th>QCD</th><th>RISK</th><th>RISK-ADJ. COST</th><th>SCORE</th><th>RECOMMENDATION</th></tr></thead><tbody>{vendors.map((v,i)=><tr className={i===1?"selected":""} key={v[0]}>{v.map((x,j)=><td key={j}>{j===0?<><strong>{x}</strong><small>{v[1]}</small></>:j===1?null:j===4?<span className={`badge b${i}`}>{x}</span>:j===7?<span className={`decision d${i}`}>{x}</span>:x}</td>)}</tr>)}</tbody></table></div><div className="formula">Formula: 30% landed cost + 15% quality + 15% delivery + 10% capacity + 10% technical + 10% risk + 5% lead time + 5% terms <a>Show full calculation</a></div></section>
    <section className="panel actions"><div className="panelhead"><div><h2>Prioritized sourcing actions</h2><p>Ranked by risk reduction and financial impact</p></div><a>View all actions →</a></div>{[["01","Approve dual-source award","RFQ-2026-001 · Welded structural assembly","$1.42M"],["02","Renegotiate material index","Apex Forge Systems · 14 components","$486K"],["03","Localize single-source bracket","CMP-044 · Eastern Ridge EV","$218K"]].map((a,i)=><div className="action" key={a[0]}><span>{a[0]}</span><div><strong>{a[1]}</strong><p>{a[2]}</p></div><div><small>EST. IMPACT</small><b>{a[3]}</b></div><em>{i<2?"HIGH":"MEDIUM"}</em><button>→</button></div>)}</section>
    <footer>Data refreshed 4 minutes ago <span>Model governance: v2.4 · Validated 12 Jun 2026 · <u>View methodology</u></span></footer>
   </div>
  </section>
  {copilot&&<div className="overlay" onClick={()=>setCopilot(false)}><section className="copilot" onClick={e=>e.stopPropagation()}><header><b>✦</b><div><strong>Source Twin Copilot</strong><small>Deterministic mode · Internal data only</small></div><button onClick={()=>setCopilot(false)}>×</button></header><article><small>AWARD EXPLANATION</small><h2>Why Northstar is the recommended primary source</h2><p>Northstar’s quote is 6.5% above Apex, but stronger delivery reliability, available capacity, and lower disruption exposure produce the best risk-adjusted outcome.</p><ul><li><b>$4.24 lower</b> risk-adjusted unit cost than Apex</li><li><b>96.8% OTIF</b> versus Apex at 82.4%</li><li><b>22/100 risk</b> with high input completeness</li></ul><div className="cite">Sources: <u>Supplier SUP-1014</u> · <u>RFQ RFQ-2026-001</u> · <u>Component CMP-001</u></div><div className="confidence">CONFIDENCE <b>High · 91%</b><i><em/></i></div></article><div className="chips"><button>Explain the cost variance</button><button>Simulate a disruption</button></div><form><input placeholder="Ask about suppliers, cost, risk, or scenarios…"/><button>↑</button></form><small className="legal">Responses cite internal records. Verify material decisions with the record owner.</small></section></div>}
 </main>
}
